# Generated by Django 4.2 on 2023-05-07 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starting_class', models.CharField(choices=[('K', 'Knight'), ('M', 'Mercenary'), ('W', 'Warrior'), ('H', 'Herald'), ('T', 'Thief'), ('A', 'Assassin'), ('S', 'Sorcerer'), ('P', 'Pyromancer'), ('C', 'Cleric'), ('D', 'Deprived')], default=0, max_length=1)),
                ('level', models.IntegerField()),
                ('story', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
