# Generated by Django 4.2 on 2023-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_starting_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='starting_gift',
            field=models.CharField(choices=[('E', 'Ember'), ('L', 'Life Ring'), ('Y', 'Young White Branch'), ('D', 'Divine Blessing'), ('H', 'Human Pine Resin')], default='E', max_length=1),
        ),
    ]
